version: "3.7"

services:
  web:
    container_name: omni-${npm-package-name}
    volumes:
      - ${PWD}:/app/web
      - /app/web/node_modules
    ports:
      - ${PORT}
    restart: always
    build: .