version: "3.7"

services:
  server:
    environment:
      - ${SPRING_DATASOURCE_URL}
      - ${SPRING_DATASOURCE_USERNAME}
      - ${SPRING_DATASOURCE_PASSWORD}
      - ${SPRING_JPA_HIBERNATE_DDL_AUTO}

  database:
    environment:
      - ${DATABASE_USER}
      - ${DATABASE_PASSWORD}
      - ${DATABASE_DB}