version: "3.7"

services:
  server:
    build: .
    ports:
      - ${API_REST_PORT}
    depends_on:
      - database

  database:
    image: "postgres:13.1-alpine"
    ports:
      - ${DATABASE_PORT}